version: "3.9"
services:
  api_sim:
    build: .
    command: uvicorn simapi.main:app --host 0.0.0.0 --port 8000
    environment:
      - API_CLIENT_ID=testclient
      - API_CLIENT_SECRET=testsecret
    ports:
      - "8000:8000"
  tests:
    build: .
    depends_on:
      - api_sim
    environment:
      - API_BASE_URL=http://api_sim:8000
      - API_CLIENT_ID=testclient
      - API_CLIENT_SECRET=testsecret
    command: pytest -q