name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: myapi-connector
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure
      - name: Lint & type check
        run: |
          pip install black flake8 mypy
          black --check .
          flake8 .
          mypy connector
      - name: Run unit tests
        run: pytest -q
      - name: Build Docker image
        run: docker build -t ${{ github.sha }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ─── Tag & push to Docker Hub ───────────────────────────────────────────
      - name: Tag & push image
        env:
          REPO: ${{ secrets.DOCKERHUB_USERNAME }}/async-api-connector   # change if you like
        run: |
          docker tag ${{ github.sha }} $REPO:${{ github.sha }}
          docker tag ${{ github.sha }} $REPO:latest
          docker push --all-tags $REPO